spring.application.name=server
server.port=${PORT:3000}
# 256-bit Hex/Base64 key used to sign your tokens.
application.security.jwt.secret-key=${JWT_SECRET_KEY}
# 15 minutes for access tokens
application.security.jwt.expiration=30000
# 7 days for refresh tokens
application.security.jwt.refresh-token.expiration=604800000

# # H2 Database
# spring.datasource.url=jdbc:h2:mem:expensesdb
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=password
# spring.h2.console.enabled=true
# # Allows Hibernate to auto-create your auth_users and users tables on startup
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
# spring.jpa.properties.hibernate.globally_quoted_identifiers=true

# Database Connection (Injected directly from Render Environment Variables)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA / Hibernate Configuration for PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true