spring.application.name=server
server.port=3000
# 256-bit Hex/Base64 key used to sign your tokens.
application.security.jwt.secret-key=jwt.secret-key=${JWT_SECRET_KEY}
# Token duration: 86400000 ms = 24 Hours
application.security.jwt.expiration=86400000

# H2 Database
spring.datasource.url=jdbc:h2:mem:expensesdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.h2.console.enabled=true
# Allows Hibernate to auto-create your auth_users and users tables on startup
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect