spring.application.name=server
server.port=${PORT:3000}
# 256-bit Hex/Base64 key used to sign your tokens.
application.security.jwt.secret-key=${JWT_SECRET_KEY}
# 15 minutes for access tokens
application.security.jwt.expiration=900000
# 7 days for refresh tokens
application.security.jwt.refresh-token.expiration=604800000

#HTTP request headers and outgoing response status codes
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG

# Database Connection (Injected directly from Render Environment Variables)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Cap connections low for Render\'s 512MB RAM and Neon\'s pooler
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=0

# Prevent broken connections caused by Neon PgBouncer timeouts
spring.datasource.hikari.idle-timeout=10000
spring.datasource.hikari.max-lifetime=30000

# Prevent Spring Boot startup freezes if Neon takes a moment to respond
spring.datasource.hikari.connection-timeout=10000
spring.datasource.hikari.initialization-fail-timeout=0

# JPA / Hibernate Configuration for PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Tomcat's thread pool
server.tomcat.threads.max=20
server.tomcat.threads.min-spare=5

# SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000

spring.mail.properties.mail.smtp.ssl.protocols=TLSv1.2
spring.mail.properties.mail.debug=true
logging.level.org.springframework.mail=DEBUG